tools:
  pyenv:
    checkBrew: true
    brew: true
    postInstall: mkdir -p ~/.pyenv/bin
    setEnv:
      PYENV_ROOT: ~/.pyenv
      # https://github.com/pyenv/pyenv/blob/master/plugins/python-build/README.md#building-for-maximum-performance
      PYTHON_CONFIGURE_OPTS: --enable-optimizations --with-lto
      PYTHON_CFLAGS: -march=native -mtune=native
    addToPath:
      - $PYENV_ROOT/bin
    evalCommand: pyenv init -
  pyenv-virtualenv:
    brew: true
    evalCommand: pyenv virtualenv-init -
  pipenv:
    brew: true
toolDeps:
  - pyenv
  - pyenv-virtualenv
  - pipenv
